# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code makes a different.
email: wing.ye.zhenrong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keep Walking. Keep Improving.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://wingyippp.github.io/blog" # the base hostname & protocol for your site
twitter_username: wingyippp
github_username:  wingyippp
permalink: /:year/:month/:day/:title/index.html
# Build settings
markdown: kramdown
